server:
  port: 8888

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/customers/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
          '[/users/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
          '[/login]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - POST
          '[/inventory/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
